<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CustomMove">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Info" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:attribute name="Index" type="xs:int" use="required"/>
            <xs:attribute name="Name" type="xs:string" use="required"/>
            <xs:attribute name="Map" type="xs:int" use="required"/>
            <xs:attribute name="X" type="xs:int" use="required"/>
            <xs:attribute name="Y" type="xs:int" use="required"/>
            <xs:attribute name="MinLevel" type="xs:int" use="required"/>
            <xs:attribute name="MaxLevel" type="xs:int" use="required"/>
            <xs:attribute name="MinReset" type="xs:int" use="required"/>
            <xs:attribute name="MaxReset" type="xs:int" use="required"/>
            <xs:attribute name="MinMReset" type="xs:int" use="required"/>
            <xs:attribute name="MaxMReset" type="xs:int" use="required"/>
            <xs:attribute name="AccountLevel" type="xs:int" use="required"/>
            <xs:attribute name="PkMove" type="xs:int" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
