<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CustomNpcCommand">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Info" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:attribute name="Index" type="xs:int" use="required"/>
            <xs:attribute name="MonsterClass" type="xs:int" use="required"/>
            <xs:attribute name="Map" type="xs:int" use="required"/>
            <xs:attribute name="X" type="xs:int" use="required"/>
            <xs:attribute name="Y" type="xs:int" use="required"/>
            <xs:attribute name="Talk" type="xs:int" use="required"/>
            <xs:attribute name="Command" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
